name: C++ CI (CMake + CTest)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Install dependecies and compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build

      - name: CMake config
        run: |
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_STANDARD=20

      - name: Compile
        run: |
          cmake --build build

      - name: Run tests with CTest
        run: |
          ctest --test-dir build --output-on-failure
